// movies
export const MOVIES_REQUEST_START = 'MOVIES_REQUEST_START';
export const MOVIES_REQUEST_SUCCESS = 'MOVIES_REQUEST_SUCCESS';
export const MOVIES_REQUEST_ERROR = 'MOVIES_REQUEST_ERROR';

export const MOVIES_APPLY_SORTING = 'MOVIES_APPLY_SORTING';
